manifest:
  remotes:
    - name: zmkfirmware
      # zmkfirmware org, repos under "projects"
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1 # set to desired version (commit, branch, tag)
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob
      revision: v0.2.1 # set to same version as zmk above
    # - name: zmk-helpers
    #   remote: urob
    #   revision: main
  self:
    path: config
