# https://docs.zephyrproject.org/latest/develop/west/manifest.html

# west.yml
# ├── remotes are github orgs
# │   └── zmkfirmware
# └── projects are repos in those orgs (github:zmkfirmware/zmk)
#     └── zmk
#         ├── from remote "zmkfirmware"
#         └── revision: commit/branch/tag

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    # - name: zmk-auto-layer
    #   remote: urob
    #   revision: v0.3.0 # set to same version as zmk above
    - name: zmk-helpers
      remote: urob
      revision: v0.3.0 # set to same version as zmk above
    # TODO: For pinning?
    # https://github.com/zmkfirmware/zephyr
    # - name: zephyr
    #   remote: zmkfirmware
    #   revision: v3.5.0+zmk-fixes
  self:
    path: config
